### ISSUE TITLE
[Acceptance Testing] Date regex bug

### ISSUE THREAD

**Issue by archthegit** [CS2103AUG2017-T09-B2/main#181]
The date field doesn't check if the date entered is a valid date. Perhaps you could try using a more valid regex, there are many you can find online.

<img width="233" alt="screen shot 2017-11-03 at 3 12 41 pm" src="https://user-images.githubusercontent.com/22144490/32363270-771afeee-c0a9-11e7-9977-e3890b8a3bf2.png">

As you can see there is no 31st in feb and also 2018 is not a leap year so there is no 29th next year in feb either

**Comment by Melvin-leo** [comment]
Is there a way to show us the regex?

**Comment by archthegit** [comment]
Hi i used a regex for birthdays, and it hasn't given me any bugs so far. You could try it or modify it further
this is the link to the PR. You should find it in a file called BirthdayCommand.Java
https://github.com/CS2103AUG2017-T15-B3/main/pull/80

**Comment by Melvin-leo** [comment]
I didnt find it in your Birthday command java, is it in another PR?

**Comment by Melvin-leo** [comment]
oh my bad i didnt scroll down

**Comment by Melvin-leo** [comment]
ok nvm i really didnt find the regex haha its it in another pr
?

**Comment by Melvin-leo** [comment]
I researched online for quite some time, but i still cant find an exact regex to use for dd-MM-yyyy HH:mm
do you know any websites to compile regex to recommend?

**Comment by Melvin-leo** [comment]
Ill try and find your code through your website. thanks for the help!

**Comment by archthegit** [comment]
Hi sorry i gave the wrong pr

<img width="976" alt="screen shot 2017-11-03 at 7 14 24 pm" src="https://user-images.githubusercontent.com/22144490/32371304-4be6f986-c0cb-11e7-9a03-a2ba6e09fed0.png">
for a quick reference given above is the regex

For more detail here is the PR link
https://github.com/CS2103AUG2017-T15-B3/main/pull/52

**Comment by Melvin-leo** [comment]
Hey thanks i managed to solve it thanks alot mate ! 💃
